# Generated by Django 4.2.1 on 2023-06-12 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guilds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('reminder_weekly', models.BooleanField(default=False)),
                ('reminder_same_day', models.BooleanField(default=False)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guilds.guild')),
                ('reminder_same_day_channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='same_day_reminder_activity_types', to='guilds.guildchannel')),
                ('reminder_weekly_channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reminder_activity_types', to='guilds.guildchannel')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('event_message', models.TextField(blank=True, null=True)),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.activitytype')),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guilds.guild')),
                ('scheduled_messages', models.ManyToManyField(blank=True, to='guilds.scheduledmessage')),
            ],
            options={
                'verbose_name_plural': 'activities',
            },
        ),
    ]
