# Generated by Django 4.2.1 on 2023-06-06 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuildChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('channel_type', models.IntegerField()),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guilds.guild')),
            ],
        ),
    ]
