# Generated by Django 4.2.1 on 2023-06-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discord_discriminator',
            field=models.TextField(null=True),
        ),
    ]
